# Generated by Django 4.0.1 on 2022-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('position', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICEPRESIDENT', 'VICEPRESIDENT'), ('SECRETARY', 'SECRETARY'), ('ASEC', 'ASEC'), ('TREASURER', 'TREASURER'), ('AUDITOR', 'AUDITOR'), ('SENATOR', 'SENATOR'), ('GOVERNOR', 'GOVERNOR')], max_length=15)),
                ('partylist', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='filepath')),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='newreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('idno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('usertype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=30)),
                ('president', models.CharField(max_length=30)),
                ('vicepresident', models.CharField(max_length=30)),
                ('secretary', models.CharField(max_length=30)),
                ('asec', models.CharField(max_length=30)),
                ('treasurer', models.CharField(max_length=30)),
                ('auditor', models.CharField(max_length=30)),
                ('senator', models.CharField(max_length=30)),
                ('governor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
    ]
