# Generated by Django 4.0.4 on 2022-05-27 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idno', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='idno')),
                ('userType', models.CharField(choices=[('STDNT', 'Student'), ('COMSELEC', 'Comelec')], default='STDNT', max_length=30, verbose_name='userType')),
                ('status', models.CharField(default='NOT VOTED', max_length=30, verbose_name='status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('position', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICEPRESIDENT', 'VICEPRESIDENT'), ('SECRETARY', 'SECRETARY'), ('ASEC', 'ASEC'), ('TREASURER', 'TREASURER'), ('AUDITOR', 'AUDITOR'), ('SENATOR', 'SENATOR'), ('GOVERNOR', 'GOVERNOR')], max_length=15)),
                ('partylist', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='filepath')),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('president', models.CharField(max_length=30)),
                ('vicepresident', models.CharField(max_length=30)),
                ('secretary', models.CharField(max_length=30)),
                ('asec', models.CharField(max_length=30)),
                ('treasurer', models.CharField(max_length=30)),
                ('auditor', models.CharField(max_length=30)),
                ('senator1', models.CharField(max_length=30)),
                ('senator2', models.CharField(max_length=30)),
                ('senator3', models.CharField(max_length=30)),
                ('senator4', models.CharField(max_length=30)),
                ('senator5', models.CharField(max_length=30)),
                ('senator6', models.CharField(max_length=30)),
                ('governor', models.CharField(max_length=30)),
                ('governor1', models.CharField(max_length=30)),
                ('governor2', models.CharField(max_length=30)),
                ('governor3', models.CharField(max_length=30)),
                ('governor4', models.CharField(max_length=30)),
                ('governor5', models.CharField(max_length=30)),
                ('governor6', models.CharField(max_length=30)),
                ('governor7', models.CharField(max_length=30)),
                ('governor8', models.CharField(max_length=30)),
                ('governor9', models.CharField(max_length=30)),
                ('idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to=settings.AUTH_USER_MODEL, verbose_name='idno')),
            ],
        ),
    ]
