# Generated by Django 4.0.1 on 2022-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vote',
            table=None,
        ),
    ]
