# Generated by Django 4.0.1 on 2022-02-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0002_alter_application_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newreg',
            name='confirm_passsword',
        ),
    ]
