# Generated by Django 4.0.1 on 2022-02-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0003_remove_newreg_confirm_passsword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='application',
            new_name='candidates',
        ),
    ]
