# Generated by Django 4.0.1 on 2022-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0004_rename_application_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='comelecreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('idno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='newreg',
            old_name='firstname',
            new_name='name',
        ),
    ]
